### PR TITLE
Support chai 2.0.0

### PR DESCRIPTION
**Pull request by ntkme**
chai 2.0.0 was just released and it includes some great improvements as well as fixes.
https://github.com/chaijs/chai/blob/master/ReleaseNotes.md

All test cases for simon-chai passed for me (chai 2.0.0 was manually installed by `npm install chai@2`).

### CODE REVIEW

**Comment by Shrugs** [comment]
+1

**Comment by halfdan** [comment]
Works for me! Would be awesome to get merged and released.

**Comment by radkodinev** [comment]
+1 Would be great!

**Comment by renatoi** [comment]
+1

**Comment by fearphage** [comment]
```` diff
+    "chai": ">=1.9.2 <3",
````

Why cap it at all? Then we'll be here when v3 comes out with a new pull request. Just remove the cap in my opinion. When chai makes a breaking change, then cap it or file a bug to fix the incompatibility.

**Comment by ntkme** [comment]
@fearphage Bumping the major version usually means a major change that breaks the compatibility. We are just lucky this time because the dropped `addChainableNoop` in chai is not used at all in this project, but there might be another major change in 3.x that breaks everything.

It's definitely better to keep it safe.

**Comment by fearphage** [comment]
@ntkme We will have to agree to disagree. It's broken now solely based on this alleged safety. If you want to be safe, you peg all the versions and you're done. No one knows if this plugin will work with chai 3.x or 5.x. Assuming it will break is the reason we're having this conversation now. 

If no one assumed it would break, everything would be functional today. This issue and pull request would not exist. This shift of responsibility allows the end user (you and I) to resolve the issue. Now it requires his/her intervention to shift the cap so it can break again in the future when we'll need his/her assistance again. In the event that chai 10.x breaks this plugin and it doesn't have a version cap, you (the end user) are free to peg chai 9.x with the latest version of this plugin. Now that choice has been taken away from you.

While I appreciate the author's work on the plugin, I prefer to not be safe guarded in this aspect when we (you and I) can fix the compatibility issues when they arise via `package.json`.

**Comment by ntkme** [comment]
@fearphage Following is the definition of Semantic Versioning (from [semver.org](http://semver.org))

Given a version number MAJOR.MINOR.PATCH, increment the:

1. MAJOR version when you make incompatible API changes,
2. MINOR version when you add functionality in a backwards-compatible manner, and
3. PATCH version when you make backwards-compatible bug fixes.

An important point here is that major version would break compatibility, while the minor version should always keep backward compatibility. That's how we assume and understand Semantic Versioning works, and that's the reason for blocking new major version to be safe.

**Comment by domenic** [comment]
Locking because I really don't care for a semver debate or more contentless +1s. Will merge, test, and release when I have time (likely the weekend).

**Pull request merged**
