### PR TITLE
Add support for sinon v4

### PR DESCRIPTION
**Pull request by Yeti-or**

### CODE REVIEW

**Comment by domenic** [comment]
[As you can see](https://travis-ci.org/domenic/sinon-chai/builds/279896519?utm_source=github_status&utm_medium=notification), the test suite fails on Sinon v4, so this is not mergeable.

**Comment by Yeti-or** [comment]
Yeah, I will investigate failing tests tomorrow, it was ok on local machine

**Comment by daffl** [comment]
Looks like another dependency (`nise `) not being installed. I had a similar problem in #108. Adding it to `devDependencies` will probably fix it but I'm still not sure why this keeps happening.

**Comment by Yeti-or** [comment]
I think it's a bug in npm and it was fixed in 5.4.2: https://github.com/npm/npm/releases/tag/v5.4.2

**Comment by Yeti-or** [comment]
steps:
```sh
$ node --version
v8.5.0
$ npm --version
5.3.0
npm install
mocha — ok
npm install sinon@^3.0.0
mocha — fail
Error: Cannot find module 'nise'

Because in nise package.json there is no more `main` field
```

**Comment by Yeti-or** [comment]
@domenic tests are green, so is it mergeable now ?

**Comment by griest024** [comment]
@Yeti-or it could be related to sinonjs/nise#10

**Comment by domenic** [comment]
Nice hack. Can we remove lolex too then?

**Comment by Yeti-or** [comment]
@domenic yes we can

**Pull request merged**
