### PR TITLE
Add support for sinon v5

### LINKED ISSUE #120: Support sinon 5

### PR DESCRIPTION
**Pull request by dostu**
Closes #120

### CODE REVIEW

**Comment by joovel** [comment]
LGTM

**Comment by voxpelli** [comment]
This should update the Travis-definition as well, see how I did it in my PR: https://github.com/domenic/sinon-chai/pull/125

Else it won't test on Sinon 5 there, and it should preferably test with both Sinon 5 and Sinon 4

I'll close my PR in favor of this one though, sorry for not noticing it before I opened mine 🙈

**Comment by dostu** [comment]
Thanks for your feedback, I've updated my PR.

**Comment by davesag** [comment]
Looking forward to this being merged so I can finally update `sinon` in my project to `v5`

**Comment by domenic** [comment]
Sinon-Chai is a spare-time project; I will hopefully have time to work on it this weekend, but even if I don't, please refrain from further +1 comments.

**Comment by davesag** [comment]
thanks @domenic — please let us know when this hits NPM.  Very eager to upgrade sinon.

**Comment by domenic** [comment]
Dang, I did indeed forget to `npm publish`. Done now.

**Pull request merged**
