### PR TITLE
updated to use Chai 4.0.0

### PR DESCRIPTION
**Pull request by jraller**
per #97 after running tests incremented version number and changed dependencies

### CODE REVIEW

**Comment by jraller** [comment]
Looks like those failures in the travis-ci were for sinon 1.4.0. I had run the local tests, but hadn't run the ci tests.

**Comment by aaronschubert0** [comment]
👍  Would be good to get rid of the warning when updating to Chai 4.0.0

**Comment by lucasfcosta** [comment]
Hmmm, maybe we could drop sinon `1.4.0` for now and stick with the latest version, at least for this plugin. I wish I could help more, but I'm not a specialist in CoffeeScript.

What do you think?

**Comment by domenic** [comment]
I think the right solution is to just update the tests with an `if` block around those tests, i.e. only test the corresponding Sinon-Chai methods if the corresponding Sinon methods exist. Sorry about the CoffeeScript; it's a legacy of a byegone age that is indeed now preventing good contributions :(.

I'll try to get to this when I have some free time.

**Comment by vsimonian** [comment]
I see the patch version bump from 2.10.0 to 2.10.1, but since this isn't a bug fix but new support, shouldn't it be a minor version bump to 2.11.0 [per semver](http://semver.org/#spec-item-6)? (And I assume this is backwards-compatible.)

**Comment by jraller** [comment]
@vsimonian I think you are right, thank you for pointing that out. Given the issues with Sinon 1.4.0 I'm wondering if I should withdraw this pull request. @domenic what is your preference?

**Comment by crookedneighbor** [comment]
@jraller Just opened a PR to fix the failing build https://github.com/domenic/sinon-chai/pull/100

**Comment by domenic** [comment]
Closing in favor of more correct https://github.com/domenic/sinon-chai/pull/101

**Pull request closed without merging**
