### PR TITLE
Support chai 3

### LINKED ISSUE #65: Chai 3.x is out, peerDependencies fail
Could you update please it? Currently it fails to install because of this.

### PR DESCRIPTION
**Pull request by gingermusketeer**
Fixes #65

### CODE REVIEW

**Comment by gingermusketeer** [comment]
Local dependencies:

```bash
sinon-chai@2.7.0 /Users/gingermusketeer/Projects/sinon-chai
├── chai@3.0.0
├── coffee-script@1.8.0
├── istanbul@0.3.14
├── jshint@2.8.0
├── mocha@1.21.5
├── opener@1.4.1
└── sinon@1.14.1
```

Test results locally:
```bash
>>  npm test                                                                                                                                                                   

> sinon-chai@2.7.0 test /Users/gingermusketeer/Projects/sinon-chai
> mocha

child_process: customFds option is deprecated, use stdio instead.


  Call arguments
    calledWith
      ✓ should throw an assertion error when the spy is not called
      ✓ should not throw when the spy is called with the correct arguments
      ✓ should not throw when the spy is called with the correct arguments and more
      ✓ should throw an assertion error when the spy is called with incorrect arguments
      ✓ should not throw when the spy is called with incorrect arguments but then correct ones
    always calledWith
      ✓ should throw an assertion error when the spy is not called
      ✓ should not throw when the spy is called with the correct arguments
      ✓ should not throw when the spy is called with the correct arguments and more
      ✓ should throw an assertion error when the spy is called with incorrect arguments
      ✓ should throw an assertion error when the spy is called with incorrect arguments but then correct ones
    calledWithExactly
      ✓ should throw an assertion error when the spy is not called
      ✓ should not throw when the spy is called with the correct arguments
      ✓ should throw an assertion error when the spy is called with the correct arguments and more
      ✓ should throw an assertion error when the spy is called with incorrect arguments
      ✓ should not throw when the spy is called with incorrect arguments but then correct ones
    always calledWithExactly
      ✓ should throw an assertion error when the spy is not called
      ✓ should not throw when the spy is called with the correct arguments
      ✓ should throw an assertion error when the spy is called with the correct arguments and more
      ✓ should throw an assertion error when the spy is called with incorrect arguments
      ✓ should throw an assertion error when the spy is called with incorrect arguments but then correct ones
    calledWithMatch
      ✓ should throw an assertion error when the spy is not called
      ✓ should not throw when the spy is called with the correct arguments
      ✓ should not throw when the spy is called with the correct arguments and more
      ✓ should throw an assertion error when the spy is called with incorrect arguments
      ✓ should not throw when the spy is called with incorrect arguments but then correct ones
    always calledWithMatch
      ✓ should throw an assertion error when the spy is not called
      ✓ should not throw when the spy is called with the correct arguments
      ✓ should not throw when the spy is called with the correct arguments and more
      ✓ should throw an assertion error when the spy is called with incorrect arguments
      ✓ should throw an assertion error when the spy is called with incorrect arguments but then correct ones

  Call context
    calledOn
      ✓ should throw an assertion error if the spy is never called
      ✓ should throw an assertion error if the spy is called without a context
      ✓ should throw an assertion error if the spy is called on the wrong context
      ✓ should not throw if the spy is called on the specified context
      ✓ should not throw if the spy is called on another context and also the specified context
    always calledOn
      ✓ should throw an assertion error if the spy is never called
      ✓ should throw an assertion error if the spy is called without a context
      ✓ should throw an assertion error if the spy is called on the wrong context
      ✓ should not throw if the spy is called on the specified context
      ✓ should throw an assertion error if the spy is called on another context and also the specified context

  Call count
    called
      ✓ should throw an assertion error when the spy is not called
      ✓ should not throw when the spy is called once
      ✓ should not throw when the spy is called twice
    not called
      ✓ should not throw when the spy is not called
      ✓ should throw an assertion error when the spy is called once
    callCount
      ✓ should throw an assertion error when the spy is not called
      ✓ should not throw an assertion error when the number of calls equals provided call count
      ✓ should throw an assertion error whenever the number of calls are not equal to provided call count
    calledOnce
      ✓ should throw an assertion error when the spy is not called
      ✓ should not throw when the spy is called once
      ✓ should throw an assertion error when the spy is called twice
    calledTwice
      ✓ should throw an assertion error when the spy is not called
      ✓ should throw an assertion error when the spy is called once
      ✓ should not throw when the spy is called twice
      ✓ should throw an assertion error when the spy is called thrice
    calledThrice
      ✓ should throw an assertion error when the spy is not called
      ✓ should throw an assertion error when the spy is called once
      ✓ should throw an assertion error when the spy is called twice
      ✓ should not throw when the spy is called thrice
      ✓ should throw an assertion error when the spy is called four times

  Call order
    spy1 calledBefore spy2
      ✓ should throw an assertion error when neither spy is called
      ✓ should not throw when only spy 1 is called
      ✓ should throw an assertion error when only spy 2 is called
      ✓ should not throw when spy 1 is called before spy 2
      ✓ should throw an assertion error when spy 1 is called after spy 2
    spy1 calledAfter spy2
      ✓ should throw an assertion error when neither spy is called
      ✓ should throw an assertion error when only spy 1 is called
      ✓ should throw an assertion error when only spy 2 is called
      ✓ should throw an assertion error when spy 1 is called before spy 2
      ✓ should not throw when spy 1 is called after spy 2

  Calling with new
    calledWithNew
      ✓ should throw an assertion error if the spy is never called
      ✓ should throw an assertion error if the spy is called without `new`
      ✓ should not throw if the spy is called with `new`
      ✓ should not throw if the spy is called with `new` and also without `new`
    always calledWithNew
      ✓ should throw an assertion error if the spy is never called
      ✓ should throw an assertion error if the spy is called without `new`
      ✓ should not throw if the spy is called with `new`
      ✓ should throw an assertion error if the spy is called with `new` and also without `new`

  Messages
    ✓ should not trigger getters for passing assertions
    about call count
      ✓ should be correct for the base cases
      ✓ should be correct for the negated cases
    about call order
      ✓ should be correct for the base cases
      ✓ should be correct for the negated cases
    about call context
      ✓ should be correct for the basic case
      ✓ should be correct for the negated case
      ✓ should be correct for the always case
    about calling with new
      ✓ should be correct for the basic case
      ✓ should be correct for the negated case
      ✓ should be correct for the always case
    about call arguments
      ✓ should be correct for the basic cases
      ✓ should be correct for the negated cases
      ✓ should be correct for the always cases
    about returning
      ✓ should be correct for the basic case
      ✓ should be correct for the negated case
      ✓ should be correct for the always case
    about throwing
      ✓ should be correct for the basic cases
      ✓ should be correct for the negated cases
      ✓ should be correct for the always cases
    when used on a non-spy/non-call
      ✓ should be informative for properties
      ✓ should be informative for methods

  Regressions
    ✓ GH-19: functions with `proxy` properties

  Returning
    returned
      ✓ should throw an assertion error if the spy does not return the correct value
      ✓ should not throw if the spy returns the correct value
      ✓ should not throw if the spy returns the correct value amongst others
    always returned
      ✓ should throw an assertion error if the spy does not return the correct value
      ✓ should not throw if the spy returns the correct value
      ✓ should throw an assertion error if the spy returns the correct value amongst others

  Throwing
    thrown()
      ✓ should throw an assertion error if the spy does not throw at all
      ✓ should not throw if the spy throws
      ✓ should not throw if the spy throws once but not the next time
    thrown(errorObject)
      ✓ should throw an assertion error if the spy does not throw at all
      ✓ should throw an assertion error if the spy throws the wrong error
      ✓ should not throw if the spy throws
      ✓ should not throw if the spy throws once but not the next time
    thrown(errorTypeString)
      ✓ should throw an assertion error if the spy does not throw at all
      ✓ should throw an assertion error if the spy throws the wrong type of error
      ✓ should not throw if the spy throws the correct type of error
      ✓ should not throw if the spy throws once but not the next time
    always thrown
      ✓ should throw an assertion error if the spy throws once but not the next time
      ✓ should throw an assertion error if the spy throws the wrong error the second time
      ✓ should not throw if the spy always throws the right error


  121 passing (455ms)
```

**Comment by domenic** [comment]
You need to update the dev dependencies as well so that it's not just on your local machine this test runs.

**Comment by gingermusketeer** [comment]
@domenic I have updated the dev dependency and changed the tests to run against all three major versions of chai this supports. Not sure if there is a better way to do it...

**Comment by Deadarius** [comment]
Can we please get this pulled as soon as possible? Thank you:)

**Comment by domenic** [comment]
You can get this pulled as soon as possible, yes. Which will not be immediately, as I have other things to do with my life than maintaining open source projects.

**Comment by Deadarius** [comment]
I did not mean to be rude and would ask you not to be as well. This pull request has only 6 additions and 3 deletions. Travis CI build passed. It takes one click to merge it. If you "have other things to do" and "maintaining open source projects" is not something you can deal with than give others opportunity to do it instead of you.

**Comment by domenic** [comment]
@Deadarius you are no longer allowed to comment on my repos.

**Comment by domenic** [comment]
Thanks @gingermusketeer, merged as 3d47b80ef8f14a0309ef8cce947bd056c4f3d159 and will be released as 2.8.0 shortly.

**Pull request closed without merging**
