### PR TITLE
Support Sinon.JS 2.0

### PR DESCRIPTION
**Pull request by sjmulder**
Tested with Sinon.JS 2.0.0-pre. All unit tests pass.

See #73

### CODE REVIEW

**Comment by domenic** [comment]
Nice. Ping me when 2.0.0 is released and I will merge and release.

**Comment by FredyC** [comment]
I am wondering how can I actually install this now. I did `npm i -D sinon@2.0.0-pre` and then tried `npm i -D https://github.com/sjmulder/sinon-chai/tarball/pr/sinon-2.0.0-pre`, however I am still getting

    npm ERR! peerinvalid The package sinon@2.0.0-pre does not satisfy its siblings' peerDependencies requirements!
    npm ERR! peerinvalid Peer sinon-chai@2.8.0 wants sinon@>=1.4.0 <3

Doesn't make any sense, '2.0.0-pre' isn't valid there?

Btw, why to even have peerDependency? It's not used in NPM3 anyway...

**Comment by brutalcrozt** [comment]
`Download Chaiv2.1.0` via [chai website](http://chaijs.com)
but i don't know anyway why in my project
chai folder -> package.json say `"version": "3.5.0"`

**Comment by pjanuario** [comment]
:+1:

**Comment by domenic** [comment]
+1 comments cause me to delay working on the feature for an additional week.

**Comment by aaronroberson** [comment]
@domenic This PR updates the peer dependency to allow v2.0.0-pre which is compatible. Can you merge this PR as-is since it is not allowing for, or related to a 2.0.0 release of sinon?

**Comment by domenic** [comment]
I'd prefer to wait for a 2.0.0 release.

**Comment by patsissons** [comment]
I couldn't get this version syntax to work (`6.9.1`/`3.10.8`), so i created a new fork with a `peerDependency` set to `>=2.0.0-pre`.

Now you can just use the following in your `packages.json` and finally be rid of that **SUPER** annoying peer dependency warning:

```
    "sinon": "marinels/sinon-chai#sinon-2pre",
```

It should be blatantly obvious to anyone using this version descriptor what the intent of the sinon package version is.

**Comment by egilsster** [comment]
@domenic Letting you know that SinonJS 2.0 has been released: https://github.com/sinonjs/sinon

**Comment by domenic** [comment]
Yes, I'll work on this on the weekend.

**Comment by levithomason** [comment]
Per https://github.com/domenic/sinon-chai/issues/73#issuecomment-286866528

>This might be of help: http://sinonjs.org/releases/v2.0.0/migrating-to-2.0/

FWIW, Semantic UI React has >7,000 unit tests utilizing `sinon-chai ^2.8.0` and works with `sinon @2.0.0` without changes, see update PR [here](https://github.com/Semantic-Org/Semantic-UI-React/pull/1464).  Just in case, I'm holding off on merging until there is official support.

**Pull request closed without merging**
