### PR TITLE
Add improved diffing for calledWith

### PR DESCRIPTION
**Pull request by jimboslicethat**
* See https://github.com/domenic/sinon-chai/issues/93 and https://github.com/sinonjs/sinon/pull/1203

### CODE REVIEW

**Comment by jimboslicethat** [comment]
Ideally I would have like to remove the `%*` on lines 142, 143, and 144. Seems like overkill when using `%D`. But testing for that seemed to be non-trivial.

**Comment by jimboslicethat** [comment]
Looks like [build job 13](https://travis-ci.org/domenic/sinon-chai/jobs/254628891) is failing with `Error: Cannot find module 'lodash'`. I suspect some flakiness in Travis. All other builds with those versions of sinon and chai seem to pass. Going to proceed with closing and reopening to see what happens.

**Comment by domenic** [comment]
Looks good. I do think it would be nice to match `%*`, but that then gets tricky not only with testing but also with the negated versions. So this will be the easiest thing for now. We'll see if anyone complains.

**Comment by demozhang1029** [comment]
Hi, Can you publish the 2.12.0 to npm? We want get this fix.

**Comment by harmon** [comment]
Thank god for this PR! Sooo much easier to diff large object changes. Thanks! Saves me lots of time.

**Pull request merged**
